### PR TITLE
adding non-horovod TF2 multi-gpu simple test

### PR DESCRIPTION
**Pull request by sparticlesteve**
Adding a test script based off the TF tutorial for multi-gpu training.

### CODE REVIEW

**Comment by sparticlesteve** [comment]
@pzharrington , this runs fine with TF 2.9 but fails with TF 2.12:
```
(ml tensorflow/2.9.0; NCCL_DEBUG=INFO sbatch scripts/tf2_multigpu.sh)
(ml tensorflow/2.12.0; NCCL_DEBUG=INFO sbatch scripts/tf2_multigpu.sh)
```

The latter gives these errors:
```
nid001020:2161631:2162430 [1] bazel-out/k8-opt/bin/external/nccl_archive/_virtual_includes/include_hdrs/alloc.h:99 NCCL WARN Cuda failure 'out of memory'
nid001020:2161631:2162430 [1] bazel-out/k8-opt/bin/external/nccl_archive/_virtual_includes/include_hdrs/alloc.h:105 NCCL WARN Failed to CUDA calloc 268435456 bytes
nid001020:2161631:2162430 [1] external/nccl_archive/src/proxy.cc:1162 NCCL WARN [Proxy Service 1] Failed to execute operation SharedInit from rank 1, retcode 1
nid001020:2161631:2162420 [1] external/nccl_archive/src/enqueue.cc:1080 NCCL WARN Cuda failure 'shared object symbol not found'

Detected at node 'NcclAllReduce' defined at (most recent call last):
    File "/global/u2/s/sfarrell/WorkAreas/ml-testing/nersc-tf-tests/tests/tf_multigpu.py", line 100, in <module>
      model.fit(train_dataset, epochs=EPOCHS, callbacks=callbacks)
    File "/global/common/software/nersc/pm-2022q4/sw/tensorflow/2.12.0/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/global/common/software/nersc/pm-2022q4/sw/tensorflow/2.12.0/lib/python3.9/site-packages/keras/engine/training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "/global/common/software/nersc/pm-2022q4/sw/tensorflow/2.12.0/lib/python3.9/site-packages/keras/engine/training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "/global/common/software/nersc/pm-2022q4/sw/tensorflow/2.12.0/lib/python3.9/site-packages/keras/engine/training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/global/common/software/nersc/pm-2022q4/sw/tensorflow/2.12.0/lib/python3.9/site-packages/keras/optimizers/utils.py", line 175, in _all_reduce_sum_fn
      return distribution.extended.batch_reduce_to(
Node: 'NcclAllReduce'

(0) UNKNOWN:  Error invoking NCCL: unhandled cuda error
	 [[{{node NcclAllReduce}}]]

0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_4467]
srun: error: nid001020: task 0: Exited with exit code 1
```

**Comment by pzharrington** [comment]
`NCCL_DEBUG` is showing
```
NCCL version 2.13.4+cudaCUDA_MAJOR.CUDA_MINOR
```
So it must be using the bundled NCCL that came with TF...however I also see
```
NCCL INFO Using network AWS Libfabric
```
So it is picking up the plugin still. Hmmmm. I guess this was working fine with horovod b/c I could build it to dynamically link against the nccl module. The tensorflow pip wheel statically links its own NCCL, is it possible it's trying to call some code path in 2.13.4 that may be deprecated or something in 2.17.x?

**Comment by sparticlesteve** [comment]
it's single node, so in principle it shouldn't need the plugin at all. Maybe it just works if we unload the nccl module. Though it's weird that the older TF module works if this is the reason.

**Comment by pzharrington** [comment]
Unloading the NCCL module does not seem to work for me. One oddity form that test I see is that there are some line numbers spit out by NCCL INFO that seem to point to specific parts of the NCCL source:
```
nid001008:1685677:1686467 [2] external/nccl_archive/src/enqueue.cc:1080 NCCL WARN Cuda failure 'shared object symbol not found'
nid001008:1685677:1686467 [2] NCCL INFO external/nccl_archive/src/group.cc:173 -> 1
nid001008:1685677:1686467 [2] NCCL INFO external/nccl_archive/src/group.cc:342 -> 1
nid001008:1685677:1686467 [2] NCCL INFO external/nccl_archive/src/group.cc:423 -> 1
nid001008:1685677:1686467 [2] NCCL INFO external/nccl_archive/src/enqueue.cc:1562 -> 1
```
However in the version printed by NCCL DEBUG (2.14.3), some of these are nonexistent. e.g. `src/enqueue.cc` only has 1531 lines total, there is no line 1562. However there is a line 1562 in nccl/2.17.1...

**Comment by pzharrington** [comment]
Some updates/fixes for this issue:

- We generally need to set `export TF_FORCE_GPU_ALLOW_GROWTH=true` to avoid the OOM error (lol, tensorflow 🤦)
- This script works fine with TF installed as `pip install tensorflow[and-cuda]`, i.e. the CUDA bundled with TF's pip wheel works
- I think the error in the TF 2.12 module is stemming from the `cudatoolkit/11.7` module. The TF website only shows [tested build configs for 11.8](https://www.tensorflow.org/install/source#gpu); if I clone the TF 2.12 module and unload the `cudatoolkit/11.7` module, then `conda install cudatoolkit==11.8`, it also works

**Comment by sparticlesteve** [comment]
I tested the simple conda env with `pip install tensorflow[and-cuda]` and the memory growth setting. While the script did complete successfully, on termination it did report some "ignored exceptions":

```
Exception ignored in: <function AtomicFunction.__del__ at 0x7f99d8a6d3f0>
Traceback (most recent call last):
  File "/global/homes/s/sfarrell/.conda/envs/tf-test/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable
```

I guess they are harmless but kinda annoying.

**Pull request merged**
